### ISSUE TITLE
TypeError handleAttributeBindingDirective(default)

### ISSUE THREAD

**Issue by jjjrmy** [alpinejs/alpine#560]
**alpinejs: ^2.3.5**

I think it is caused by `input[type="range"]`

**Browsers:** Mobile Safari 13.1, Chrome Mobile iOS 81.0.4044

https://sentry.io/share/issue/117fa5d91e5441f69b97e0da9d811b25/
```
TypeError: Type error
  at handleAttributeBindingDirective(/default.js:57:129)
  at ? (/default.js:169:110)
  at forEach([native code])
  at resolveBoundAttributes(/default.js:169:14)
  at updateElement(/default.js:166:56)
  at ? (/default.js:163:173)
  at walk(/default.js:17:39)
  at walk(/default.js:17:105)
  at walk(/default.js:17:105)
  at walkAndSkipNestedComponents(/default.js:158:81)
  at updateElements(/default.js:163:73)
  at ? (/default.js:155:95)
  at later(/default.js:18:142)
```

**Comment by SimoTod** [comment]
Are you sure about the version? Source code on your website says Alpine v2.3.1.
There was a bug on old Alpine versions but it was fixed.

**Comment by jjjrmy** [comment]
@SimoTod I think it was cache issue with Cloudflare. I purged, we'll see if it continues the next few days..
